### ISSUE TITLE
main broken: cqlite-core --lib missing serial_test::serial import after #2437/#2438 merge race

### ISSUE THREAD

**Issue by pmcfadin** [pmcfadin/cqlite#2462]
## What
`origin/main` at `710dde190` fails `cargo clippy`/`cargo test -p cqlite-core --lib`
(and therefore `scripts/agent-gate.sh` / `--lite`) for every worker on every machine:
```
error[E0433]: failed to resolve: use of undeclared crate or module `serial_test`
  --> cqlite-core/src/storage/sstable/reader/data_access/full_index_stream_tests.rs:326
   |
   #[serial(work_counters)]
```
(4 occurrences: lines 326/373/416/611.)

## Root cause
A merge race between two independently-green PRs:
- `088ad1960` (#2438) removed `use serial_test::serial;` from
  `cqlite-core/src/storage/sstable/reader/data_access/full_index_stream_tests.rs`
  (presumably as an unused-import cleanup, correct AT THAT COMMIT).
- `70bdc178e` (#2437) added 4 new `#[serial(work_counters)]` attributes to the SAME
  file (lines 326/373/416/611), branched BEFORE #2438's import removal, so #2437's
  own gate ran green.

Neither PR's individual diff was wrong in isolation; the merged result on `main` is
orphaned — #2437 rebased/merged after #2438 without picking up the import removal,
or vice versa, and neither round re-ran the full gate against the FINAL merged tree.

## Fix
One-liner: re-add `use serial_test::serial;` near the top of
`cqlite-core/src/storage/sstable/reader/data_access/full_index_stream_tests.rs`
(was at line 20). Confirm `cargo clippy --workspace --all-targets --all-features`
and the `cqlite-core --lib` test target both go green.

## Impact
Every worker's `--lite` and full gate on `cqlite-core` fails until this lands —
found while running the lite gate for an unrelated issue (#1818), whose own change
was independently confirmed clean (isolated `cargo test` of just its new test target
passed). Routing: oracle-driven, trivial, no OpenSpec.

## Acceptance criteria
- [ ] `use serial_test::serial;` restored in
      `full_index_stream_tests.rs`.
- [ ] `cargo clippy --workspace --all-targets --all-features` (matching CI's
      `RUSTFLAGS="-D warnings"`) passes.
- [ ] `cargo test -p cqlite-core --lib` passes.
- [ ] `scripts/agent-gate.sh --lite` PASSes on a clean worktree off `main`.

**Comment by pmcfadin** [comment]
Duplicate of #2463 (same broken-main serial_test import, filed in parallel by another session). Fix is PR #2465, in endgame now.
